spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/must
    username: postgres                                   
    password: postgres                                   
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
  main:
    banner-mode: "LOG"
  output:
    ansi:
      enabled: always


logging:
  level:
    root: ERROR
    '[org.springframework.boot]': INFO
    '[org.hibernate]': WARN


debug: false
